name: Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Docker image URI
        run: echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT_NAME }}_tf:latest" >> $GITHUB_ENV

      - name: Docker login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      
      - name: Push docker image to AWS ECR
        run: docker push ${{ env.IMAGE_URI }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init -upgrade -backend-config="key=convbot/master/infra.tfstate"
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra