name: Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform -chdir=../../infra init

      - name: Terraform Plan
        run: terraform -chdir=../../infra plan
      
      - name: Terraform Apply
        run: terraform -chdir=../../infra apply
